version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: laravel_app
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    networks:
      - appnet
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - appnet

  db:
    image: mysql:8
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet

  vue:
    image: node:18
    container_name: vue_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - appnet

volumes:
  dbdata:

networks:
  appnet:
